site_name: Pykour
site_description: Pykour is modern, fast, and easy to use REST framework for Python.
site_url: https://pykour.com/
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    - scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
          icon: material/toggle-switch
          name: Switch to light mode
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - announce.dismiss
    - navigation.tabs
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.suggest
    - toc.follow
nav:
  - Home: index.md
  - User's Guide:
    - Installation: installation.md
    - Pykour CLI: cli.md
    - Quickstart:
      - Introduction: quickstart/introduction.md
      - Routes: quickstart/routes.md
      - Schema: quickstart/schema.md
    - Routing:
      - Introduction: routing/introduction.md
      - Router: routing/router.md
      - Schemas: routing/schemas.md
    - Configuration:
      - Introduction: configuration/introduction.md
      - Config: configuration/config.md
    - Database:
      - Introduction: database/introduction.md
      - Connection: database/connection.md
    - Middleware:
      - Introduction: middleware/introduction.md
      - UUID Middleware: middleware/uuid.md
      - GZIP Middleware: middleware/gzip.md
    - Testing:
        - Introduction: testing/introduction.md
#  - API Docs:
#    - core:
#      - Pykour: api/pykour.md
#      - Router: api/router.md
#      - Request: api/request.md
#      - Response: api/response.md
#      - URL: api/url.md
#      - BaseSchema: api/baseschema.md
#    - exceptions:
#      - HTTPException: api/httpexception.md
#      - ResourceNotFoundException: api/resourcenotfoundexception.md
  - Release Notes: release-notes.md
repo_name: pykour/pykour
repo_url: https://github.com/pykour/pykour
edit_uri: ''
plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [./src]
          options:
            members_order: source
            separate_signature: true
            filters: ["!^_"]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_signature_annotations: true
            signature_crossrefs: true
          import:
            - https://docs.python.org/3/objects.inv
markdown_extensions:
  toc:
    permalink: true
extra:
  analytics:
    provider: google
    property: G-X9TGYEY0S2
