[project]
name = "pykour"
version = "1.0.0"
description = "Pykour is modern, fast, and easy to use REST framework for Python."
authors = [
  { name = "Takashi Yamashina", email = "takashi.yamashina@gmail.com" },
]
requires-python = ">=3.10"
readme = "README.md"
dependencies = []

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=8.3.5",
    "pytest-asyncio>=1.0.0",
]

[tool.uv]
default-groups = []

[tool.hatch.build.targets.sdist]
include = ["src/pykour"]

[tool.hatch.build.targets.wheel]
include = ["src/pykour"]

[tool.hatch.build.targets.wheel.sources]
"src/pykour" = "pykour"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
