"""Table and Column definitions for migrations."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

from pykour.db.migrations.types import ColumnType

if TYPE_CHECKING:
    from pykour.db.access_policy.policy import AccessPolicy


@dataclass
class Column:
    """Column definition for table schema.

    Attributes:
        type: Column type (e.g., Integer(), String(100)).
        primary_key: Whether this is the primary key.
        nullable: Whether the column allows NULL.
        unique: Whether the column has a unique constraint.
        default: Default value for the column.
        autoincrement: Whether the column auto-increments.
        name: Column name (set automatically by TableMeta).
        auto_now_add: If True, set to current UTC time on INSERT only.
        auto_now: If True, set to current UTC time on INSERT and UPDATE.
        auto_set_on_insert: Value to set on INSERT only (e.g., ":user_id").
        auto_set: Value to set on INSERT and UPDATE (e.g., ":tenant_id").

    Auto-set values can be:
        - ":now" - Current UTC time
        - ":user_id" - User ID from policy context
        - ":tenant_id" - Tenant ID from policy context
        - ":organization_id" - Organization ID from policy context
        - "literal" - A literal string value
    """

    type: ColumnType
    primary_key: bool = False
    nullable: bool = True
    unique: bool = False
    default: Any = None
    autoincrement: bool = False
    name: str = ""
    # Auto-set options for INSERT/UPDATE
    auto_now_add: bool = False
    auto_now: bool = False
    auto_set_on_insert: str | None = None
    auto_set: str | None = None

    def to_sql(self, driver: str) -> str:
        """Generate SQL column definition."""
        parts = [self.name, self.type.to_sql(driver)]

        if self.primary_key:
            parts.append("PRIMARY KEY")
            if self.autoincrement:
                if driver == "sqlite":
                    parts.append("AUTOINCREMENT")
                elif driver == "postgresql":
                    pass
                elif driver == "mysql":
                    parts.append("AUTO_INCREMENT")
        elif not self.nullable:
            parts.append("NOT NULL")

        if self.unique and not self.primary_key:
            parts.append("UNIQUE")

        if self.default is not None and not self.autoincrement:
            if isinstance(self.default, bool):
                parts.append(f"DEFAULT {1 if self.default else 0}")
            elif isinstance(self.default, str):
                if self.default.lower() in ("now()", "current_timestamp"):
                    parts.append("DEFAULT CURRENT_TIMESTAMP")
                else:
                    # Escape single quotes to prevent SQL injection
                    escaped = self.default.replace("'", "''")
                    parts.append(f"DEFAULT '{escaped}'")
            else:
                parts.append(f"DEFAULT {self.default}")

        return " ".join(parts)


@dataclass
class ColumnDef:
    """Column definition for op.column() helper."""

    name: str
    type_sql: str
    primary_key: bool = False
    nullable: bool = True
    unique: bool = False
    default: Any = None
    autoincrement: bool = False

    def to_sql(self, driver: str) -> str:
        """Generate SQL column definition."""
        parts = [self.name, self.type_sql]

        if self.primary_key:
            parts.append("PRIMARY KEY")
            if self.autoincrement:
                if driver == "sqlite":
                    parts.append("AUTOINCREMENT")
                elif driver == "mysql":
                    parts.append("AUTO_INCREMENT")
                elif driver == "postgresql":
                    parts.append("GENERATED BY DEFAULT AS IDENTITY")

        if not self.nullable and not self.primary_key:
            parts.append("NOT NULL")

        if self.unique and not self.primary_key:
            parts.append("UNIQUE")

        if self.default is not None and not self.autoincrement:
            if isinstance(self.default, bool):
                parts.append(f"DEFAULT {1 if self.default else 0}")
            elif isinstance(self.default, str):
                if self.default.lower() in ("now()", "current_timestamp"):
                    parts.append("DEFAULT CURRENT_TIMESTAMP")
                else:
                    # Escape single quotes to prevent SQL injection
                    escaped = self.default.replace("'", "''")
                    parts.append(f"DEFAULT '{escaped}'")
            else:
                parts.append(f"DEFAULT {self.default}")

        return " ".join(parts)


@dataclass
class IndexDef:
    """Index definition (from introspection, Meta class, or op.create_index).

    This is an internal class used for index representation.
    Users should use Meta.unique_together and Meta.search_keys instead.
    """

    name: str
    table: str
    columns: list[str]
    unique: bool = False
    where: str | None = None


@dataclass
class TableInfo:
    """Information about a database table (from introspection)."""

    name: str
    columns: list[ColumnInfo] = field(default_factory=list)
    indexes: list[IndexDef] = field(default_factory=list)
    primary_key: list[str] = field(default_factory=list)


@dataclass
class ColumnInfo:
    """Information about a database column (from introspection)."""

    name: str
    type: str
    nullable: bool = True
    default: Any = None
    autoincrement: bool = False
    primary_key: bool = False


class TableMeta(type):
    """Metaclass for Table to collect column, index, and access policy definitions.

    This metaclass processes:
    - Column instances as column definitions
    - Meta inner class for unique_together, search_keys, and access_policy
    - __access_policy__ attribute (deprecated, use Meta.access_policy instead)
    """

    def __new__(
        mcs,
        name: str,
        bases: tuple[type, ...],
        namespace: dict[str, Any],
    ) -> TableMeta:
        columns: dict[str, Column] = {}
        indexes: list[IndexDef] = []
        access_policy: "AccessPolicy | None" = None
        unique_together: list[tuple[str, ...]] = []
        search_keys: list[list[str]] = []

        # Collect columns
        for key, value in namespace.items():
            if isinstance(value, Column):
                value.name = key
                columns[key] = value

        # Get tablename for index naming
        tablename = namespace.get("__tablename__", name.lower())

        # Process Meta class if present
        meta_class = namespace.get("Meta")
        if meta_class is not None:
            # Extract unique_together
            if hasattr(meta_class, "unique_together"):
                raw_unique = getattr(meta_class, "unique_together")
                for item in raw_unique:
                    if isinstance(item, (list, tuple)):
                        unique_together.append(tuple(item))

            # Extract search_keys
            if hasattr(meta_class, "search_keys"):
                raw_search = getattr(meta_class, "search_keys")
                for item in raw_search:
                    if isinstance(item, (list, tuple)):
                        search_keys.append(list(item))

            # Extract access_policy from Meta
            if hasattr(meta_class, "access_policy"):
                access_policy = getattr(meta_class, "access_policy")

        # Fall back to __access_policy__ if Meta.access_policy not set
        if access_policy is None and "__access_policy__" in namespace:
            access_policy = namespace["__access_policy__"]

        # Convert unique_together to IndexDef
        for i, cols in enumerate(unique_together):
            col_names = "_".join(cols)
            idx_name = f"uq_{tablename}_{col_names}"
            indexes.append(
                IndexDef(
                    name=idx_name,
                    table=tablename,
                    columns=list(cols),
                    unique=True,
                )
            )

        # Convert search_keys to IndexDef
        for i, cols in enumerate(search_keys):
            col_names = "_".join(cols)
            idx_name = f"idx_{tablename}_{col_names}"
            indexes.append(
                IndexDef(
                    name=idx_name,
                    table=tablename,
                    columns=cols,
                    unique=False,
                )
            )

        namespace["_columns"] = columns
        namespace["_indexes"] = indexes
        namespace["_access_policy"] = access_policy
        namespace["_unique_together"] = unique_together
        namespace["_search_keys"] = search_keys
        return super().__new__(mcs, name, bases, namespace)


class Table(metaclass=TableMeta):
    """Base class for table definitions.

    Example with Meta class (recommended):
        from pykour.db.migrations import Table, Column
        from pykour.db.migrations.types import Integer, String, DateTime
        from pykour.db.access_policy import AccessPolicy

        class OrderTable(Table):
            __tablename__ = "orders"

            id = Column(Integer(), primary_key=True, autoincrement=True)
            tenant_id = Column(String(36), nullable=False)
            email = Column(String(255), nullable=False)
            domain = Column(String(100), nullable=False)
            created_at = Column(DateTime(), auto_now_add=True)
            updated_at = Column(DateTime(), auto_now=True)

            class Meta:
                # Composite unique constraints (creates UNIQUE INDEX)
                unique_together = [
                    ("email", "domain"),
                    ("tenant_id", "email"),
                ]

                # Search keys (creates INDEX)
                search_keys = [
                    ["tenant_id"],
                    ["email", "created_at"],
                ]

                # Row-level security (RLS)
                access_policy = AccessPolicy(
                    select=["tenant_id = :tenant_id"],
                    insert=["tenant_id = :tenant_id"],
                    auto_set={"tenant_id": ":tenant_id"},
                )

    Legacy example with __access_policy__ (still supported):
        class OrderTable(Table):
            __tablename__ = "orders"
            __access_policy__ = AccessPolicy(
                select=["tenant_id = :tenant_id"],
            )

            id = Column(Integer(), primary_key=True, autoincrement=True)
            tenant_id = Column(String(36), nullable=False)
    """

    __tablename__: str
    __access_policy__: "AccessPolicy | None" = None
    _columns: dict[str, Column]
    _indexes: list[IndexDef]
    _access_policy: "AccessPolicy | None"
    _unique_together: list[tuple[str, ...]]
    _search_keys: list[list[str]]

    @classmethod
    def get_tablename(cls) -> str:
        """Get the table name."""
        return getattr(cls, "__tablename__", cls.__name__.lower())

    @classmethod
    def get_columns(cls) -> dict[str, Column]:
        """Get all column definitions."""
        return cls._columns.copy()

    @classmethod
    def get_column(cls, name: str) -> Column | None:
        """Get a column by name."""
        return cls._columns.get(name)

    @classmethod
    def get_indexes(cls) -> list[IndexDef]:
        """Get all index definitions.

        Returns:
            List of IndexDef objects generated from unique_together and search_keys.
        """
        return cls._indexes.copy()

    @classmethod
    def get_unique_together(cls) -> list[tuple[str, ...]]:
        """Get unique together constraints.

        Returns:
            List of tuples, each containing column names for a unique constraint.
        """
        return cls._unique_together.copy()

    @classmethod
    def get_search_keys(cls) -> list[list[str]]:
        """Get search key definitions.

        Returns:
            List of lists, each containing column names for an index.
        """
        return [cols.copy() for cols in cls._search_keys]

    @classmethod
    def get_access_policy(cls) -> "AccessPolicy | None":
        """Get the access policy for this table."""
        return cls._access_policy

    @classmethod
    def get_auto_set_columns(cls, on_insert: bool = True) -> dict[str, Column]:
        """Get columns with auto-set options.

        Args:
            on_insert: If True, include auto_now_add and auto_set_on_insert.
                       If False, only include auto_now and auto_set (for UPDATE).

        Returns:
            Dictionary of column name to Column for columns that should be auto-set.
        """
        result: dict[str, Column] = {}
        for name, col in cls._columns.items():
            if on_insert:
                # INSERT: include auto_now_add, auto_now, auto_set_on_insert, auto_set
                if col.auto_now_add or col.auto_now:
                    result[name] = col
                elif col.auto_set_on_insert or col.auto_set:
                    result[name] = col
            else:
                # UPDATE: only include auto_now and auto_set
                if col.auto_now:
                    result[name] = col
                elif col.auto_set:
                    result[name] = col
        return result
