"""Tests for field inference module."""

from __future__ import annotations


from pykour.db.migrations.table import Column, Table
from pykour.db.migrations.types import (
    Boolean,
    DateTime,
    Integer,
    String,
    Text,
)
from pykour.generators.field_inference import (
    AUTO_GENERATED_COLUMNS,
    COLUMN_TYPE_TO_STR,
    FieldInferrer,
)


class UserTable(Table):
    """Sample user table for testing."""

    __tablename__ = "users"

    id = Column(Integer(), primary_key=True, autoincrement=True)
    name = Column(String(100), nullable=False)
    email = Column(String(255), nullable=False)
    bio = Column(Text(), nullable=True)
    active = Column(Boolean(), default=True)
    created_at = Column(DateTime(), default="CURRENT_TIMESTAMP")


class ProductTable(Table):
    """Sample product table for testing."""

    __tablename__ = "products"

    id = Column(Integer(), primary_key=True, autoincrement=True)
    title = Column(String(200), nullable=False)
    description = Column(Text(), nullable=True)
    price = Column(Integer(), nullable=False)
    in_stock = Column(Boolean(), default=True)


class TestColumnTypeMapping:
    """Tests for column type to Python type string mapping."""

    def test_integer_type(self) -> None:
        """Integer maps to 'int'."""
        assert COLUMN_TYPE_TO_STR[Integer] == "int"

    def test_string_type(self) -> None:
        """String maps to 'str'."""
        assert COLUMN_TYPE_TO_STR[String] == "str"

    def test_boolean_type(self) -> None:
        """Boolean maps to 'bool'."""
        assert COLUMN_TYPE_TO_STR[Boolean] == "bool"

    def test_datetime_type(self) -> None:
        """DateTime maps to 'str'."""
        assert COLUMN_TYPE_TO_STR[DateTime] == "str"

    def test_text_type(self) -> None:
        """Text maps to 'str'."""
        assert COLUMN_TYPE_TO_STR[Text] == "str"


class TestAutoGeneratedColumns:
    """Tests for auto-generated column detection."""

    def test_id_is_auto_generated(self) -> None:
        """'id' column is auto-generated."""
        assert "id" in AUTO_GENERATED_COLUMNS

    def test_created_at_is_auto_generated(self) -> None:
        """'created_at' column is auto-generated."""
        assert "created_at" in AUTO_GENERATED_COLUMNS

    def test_updated_at_is_auto_generated(self) -> None:
        """'updated_at' column is auto-generated."""
        assert "updated_at" in AUTO_GENERATED_COLUMNS


class TestFieldInferrer:
    """Tests for FieldInferrer class."""

    def test_infer_from_table_basic(self) -> None:
        """Infer fields from a basic Table definition."""
        inferrer = FieldInferrer()
        fields = inferrer.infer_from_table(UserTable)

        assert len(fields) == 6

        field_names = [f.name for f in fields]
        assert "id" in field_names
        assert "name" in field_names
        assert "email" in field_names
        assert "bio" in field_names
        assert "active" in field_names
        assert "created_at" in field_names

    def test_autoincrement_primary_key_is_auto_generated(self) -> None:
        """Autoincrement primary key is detected as auto-generated."""
        inferrer = FieldInferrer()
        fields = inferrer.infer_from_table(UserTable)

        id_field = next(f for f in fields if f.name == "id")
        assert id_field.is_primary_key is True
        assert id_field.is_auto_generated is True

    def test_created_at_is_auto_generated(self) -> None:
        """created_at column is detected as auto-generated."""
        inferrer = FieldInferrer()
        fields = inferrer.infer_from_table(UserTable)

        created_at_field = next(f for f in fields if f.name == "created_at")
        assert created_at_field.is_auto_generated is True

    def test_string_max_length_extraction(self) -> None:
        """String max_length is extracted from Column definition."""
        inferrer = FieldInferrer()
        fields = inferrer.infer_from_table(UserTable)

        name_field = next(f for f in fields if f.name == "name")
        assert name_field.max_length == 100

        email_field = next(f for f in fields if f.name == "email")
        assert email_field.max_length == 255

    def test_nullable_detection(self) -> None:
        """Nullable attribute is correctly detected."""
        inferrer = FieldInferrer()
        fields = inferrer.infer_from_table(UserTable)

        name_field = next(f for f in fields if f.name == "name")
        assert name_field.nullable is False

        bio_field = next(f for f in fields if f.name == "bio")
        assert bio_field.nullable is True

    def test_default_value_extraction(self) -> None:
        """Default values are correctly extracted."""
        inferrer = FieldInferrer()
        fields = inferrer.infer_from_table(UserTable)

        active_field = next(f for f in fields if f.name == "active")
        assert active_field.default is True

    def test_python_type_inference(self) -> None:
        """Python types are correctly inferred."""
        inferrer = FieldInferrer()
        fields = inferrer.infer_from_table(UserTable)

        id_field = next(f for f in fields if f.name == "id")
        assert id_field.python_type == "int"

        name_field = next(f for f in fields if f.name == "name")
        assert name_field.python_type == "str"

        active_field = next(f for f in fields if f.name == "active")
        assert active_field.python_type == "bool"


class TestGenerateCreateFields:
    """Tests for create schema field generation."""

    def test_excludes_autoincrement_primary_key(self) -> None:
        """Autoincrement primary key is excluded from create schema."""
        inferrer = FieldInferrer()
        fields = inferrer.infer_from_table(UserTable)
        create_fields = inferrer.generate_create_fields(fields)

        assert "id:" not in create_fields

    def test_excludes_auto_generated_columns(self) -> None:
        """Auto-generated columns are excluded from create schema."""
        inferrer = FieldInferrer()
        fields = inferrer.infer_from_table(UserTable)
        create_fields = inferrer.generate_create_fields(fields)

        assert "created_at:" not in create_fields

    def test_includes_required_fields(self) -> None:
        """Required fields are included without default."""
        inferrer = FieldInferrer()
        fields = inferrer.infer_from_table(UserTable)
        create_fields = inferrer.generate_create_fields(fields)

        assert "name: str" in create_fields
        assert "email: str" in create_fields

    def test_includes_max_length_constraint(self) -> None:
        """max_length constraint is included for String fields."""
        inferrer = FieldInferrer()
        fields = inferrer.infer_from_table(UserTable)
        create_fields = inferrer.generate_create_fields(fields)

        assert "max_length=100" in create_fields
        assert "max_length=255" in create_fields

    def test_includes_default_value(self) -> None:
        """Default values are included in field definition."""
        inferrer = FieldInferrer()
        fields = inferrer.infer_from_table(UserTable)
        create_fields = inferrer.generate_create_fields(fields)

        assert "active: bool" in create_fields
        assert "default=True" in create_fields

    def test_nullable_fields_have_optional_type(self) -> None:
        """Nullable fields have Optional type annotation."""
        inferrer = FieldInferrer()
        fields = inferrer.infer_from_table(UserTable)
        create_fields = inferrer.generate_create_fields(fields)

        assert "bio: str | None" in create_fields

    def test_generates_valid_python_code(self) -> None:
        """Generated code is valid Python syntax."""
        inferrer = FieldInferrer()
        fields = inferrer.infer_from_table(UserTable)
        create_fields = inferrer.generate_create_fields(fields)

        # Check indentation
        for line in create_fields.split("\n"):
            if line.strip():
                assert line.startswith("    ")


class TestGenerateUpdateFields:
    """Tests for update schema field generation."""

    def test_excludes_primary_key(self) -> None:
        """Primary key is excluded from update schema."""
        inferrer = FieldInferrer()
        fields = inferrer.infer_from_table(UserTable)
        update_fields = inferrer.generate_update_fields(fields)

        assert "id:" not in update_fields

    def test_excludes_auto_generated_columns(self) -> None:
        """Auto-generated columns are excluded from update schema."""
        inferrer = FieldInferrer()
        fields = inferrer.infer_from_table(UserTable)
        update_fields = inferrer.generate_update_fields(fields)

        assert "created_at:" not in update_fields

    def test_all_fields_are_optional(self) -> None:
        """All fields in update schema have Optional type."""
        inferrer = FieldInferrer()
        fields = inferrer.infer_from_table(UserTable)
        update_fields = inferrer.generate_update_fields(fields)

        # Check that all field types are Optional
        assert "name: str | None" in update_fields
        assert "email: str | None" in update_fields
        assert "active: bool | None" in update_fields

    def test_all_fields_have_default_none(self) -> None:
        """All fields in update schema have default=None."""
        inferrer = FieldInferrer()
        fields = inferrer.infer_from_table(UserTable)
        update_fields = inferrer.generate_update_fields(fields)

        # Count occurrences of default=None
        assert update_fields.count("default=None") >= 3


class TestEmptyTable:
    """Tests for edge cases with minimal tables."""

    def test_table_with_only_id(self) -> None:
        """Table with only auto-generated id returns 'pass' for create."""

        class IdOnlyTable(Table):
            __tablename__ = "id_only"
            id = Column(Integer(), primary_key=True, autoincrement=True)

        inferrer = FieldInferrer()
        fields = inferrer.infer_from_table(IdOnlyTable)
        create_fields = inferrer.generate_create_fields(fields)
        update_fields = inferrer.generate_update_fields(fields)

        assert create_fields == "    pass"
        assert update_fields == "    pass"


class TestProductTable:
    """Tests using ProductTable to verify different schema patterns."""

    def test_product_create_fields(self) -> None:
        """Product create fields are correctly generated."""
        inferrer = FieldInferrer()
        fields = inferrer.infer_from_table(ProductTable)
        create_fields = inferrer.generate_create_fields(fields)

        assert "title: str" in create_fields
        assert "max_length=200" in create_fields
        assert "price: int" in create_fields
        assert "in_stock: bool" in create_fields
        assert "default=True" in create_fields
        assert "id:" not in create_fields

    def test_product_update_fields(self) -> None:
        """Product update fields are all Optional."""
        inferrer = FieldInferrer()
        fields = inferrer.infer_from_table(ProductTable)
        update_fields = inferrer.generate_update_fields(fields)

        assert "title: str | None" in update_fields
        assert "price: int | None" in update_fields
        assert "in_stock: bool | None" in update_fields
