name: Check CHANGELOG Update

on:
  pull_request:
    branches:
      - '**'

jobs:
  check-changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check if CHANGELOG was updated
      run: |
        git fetch origin main
        # Check if CHANGELOG was updated
        if git diff --name-only origin/main HEAD | grep -q "CHANGELOG"; then
          echo "CHANGELOG updated."
        else
          echo "CHANGELOG not updated!"
          exit 1
        fi
