name: Restrict PR Merge Targets

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - main
      - '**'

jobs:
  check-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Check target branch for PR
      run: |
        TARGET_BRANCH="${{ github.event.pull_request.base.ref }}"
        SOURCE_BRANCH="${{ github.event.pull_request.head.ref }}"

        if [[ "$TARGET_BRANCH" == "main" ]]; then
          if [[ ! "$SOURCE_BRANCH" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Only branches matching 'vX.X.X' pattern can be merged into main."
            exit 1
          fi
        elif [[ ! "$TARGET_BRANCH" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Error: Only branches matching 'vX.X.X' pattern can be merged into other 'vX.X.X' branches."
          exit 1
        fi

    - name: Allow merge
      run: echo "Merge allowed."
